cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('add/<int:product_id>/', views.add_cart, name='add_cart'),
	path('', views.cart_detail, name='cart_detail'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
	path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
	path('thanks/<int:order_id>/', views.thanks, name='thanks'),
	path('history/', views.orderHistory, name='order_history'),
	path('<int:order_id>/', views.viewOrder, name='order_detail'),
]

perfectcushion/urls.py
from django.contrib.auth import views as authViews
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('account/create/', views.signupView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),
    #This path will request the customer to type in the email address he or she wants to receive the new instructions to reset the password
    path('account/password-reset/',
    authViews.PasswordResetView.as_view(template_name='accounts/reset_password.html'),
    name='password_reset'),
 
#This will inform the customer a new email has been sent with the instruction
    path('account/password-reset/done/',
     authViews.PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html'),
     name='password_reset_done'),
 
#This path will provide a specific url with a base64 hash as well as with a token
    path('account/password-reset-confirm/<uidb64>/<token>/',
     authViews.PasswordResetConfirmView.as_view(template_name='accounts/reset_password_confirm.html'),
     name='password_reset_confirm'),
 
#This will inform the customer that the password has been changed
    path('account/password-reset-complete/',
     authViews.PasswordResetCompleteView.as_view(template_name='accounts/reset_password_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns = [
	path('', views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
	path('', views.allProdCat, name='allProdCat'),
	path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
	path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block metadescription %}{% endblock %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<div class="container">
		<div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
			{% include 'top-navbar.html' %}
		</div>
		{% include 'header.html' %}
		{% include 'navbar.html' %}
		{% block content %}
		{% endblock %}
	</div>
		{% include 'footer.html' %}
	<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/footer.html
{% block content %}
  <!-- banner-2 -->
  <div class="page-head_agile_info_w3l">

  </div>
  <!-- //banner-2 -->
  <!-- page -->
  <div class="services-breadcrumb">
    <div class="agile_inner_breadcrumb">
      <div class="container">
        <ul class="w3_short">
          <li>
            <a href="index.html">Home</a>
            <i>|</i>
          </li>
          <li>About Us</li>
        </ul>
      </div>
    </div>
  </div>
  <!-- //page -->
  <!-- about page -->
  <!-- welcome -->
  <div class="welcome">
    <div class="container">
      <!-- tittle heading -->
      <h3 class="tittle-w3l">Welcome to our Site
        <span class="heading-style">
          <i></i>
          <i></i>
          <i></i>
        </span>
      </h3>
      <!-- //tittle heading -->
      <div class="w3l-welcome-info">
        <div class="col-sm-6 col-xs-6 welcome-grids">
          <div class="welcome-img">
            <img src="images/about.jpg" class="img-responsive zoom-img" alt="">
          </div>
        </div>
        <div class="col-sm-6 col-xs-6 welcome-grids">
          <div class="welcome-img">
            <img src="images/about2.jpg" class="img-responsive zoom-img" alt="">
          </div>
        </div>
        <div class="clearfix"> </div>
      </div>
      <div class="w3l-welcome-text">
        <p>Nam libero tempore cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus
          omnis optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.Sed ut perspiciatis unde omnis iste
          natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis
          et quasi architecto beatae vitae </p>
        <p>libero tempore cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus
          omnis optio cumque nihil impedit </p>
      </div>
    </div>
  </div>
  <!-- //welcome -->
  <!-- video -->
  <div class="about">
    <div class="container">
      <!-- tittle heading -->
      <h3 class="tittle-w3l">Our Video
        <span class="heading-style">
          <i></i>
          <i></i>
          <i></i>
        </span>
      </h3>
      <!-- //tittle heading -->
      <div class="about-tp">
        <div class="col-md-8 about-agileits-w3layouts-left">
          <iframe src="https://player.vimeo.com/video/15520702?color=ffffff&title=0&byline=0"></iframe>
        </div>
        <div class="col-md-4 about-agileits-w3layouts-right">
          <div class="img-video-about">
            <img src="images/videoimg2.png" alt="">
          </div>
          <h4>Grocery Shoppy</h4>
          <p>No.1 Leading E-commerce marketplace with over 70 million Products</p>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
  <!-- //video-->
  <!-- //about page -->
  
  {% endblock %}

templates/header.html
{% load staticfiles %}
<header>
	<center>
		<a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="Perfect Cushion Store"></a>
	</center>
</header>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
        </div>
      </li>
      {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

templates/top-navbar.html
<div class="container">
	<div class="my_custom_menu">
		<ul>
			{% if request.user.is_authenticated and request.user.first_name %}
			<li>
				Welcome, <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.first_name }} <i class="fas fa-user-circle"></i></a>
				<div class="dropdown-menu dropdown-menu-right">
					<a href="{% url 'order:order_history' %}" class="dropdown-item">Order History</a>
				</div>
			</li>
			<li>
				<a href="{% url 'signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
			</li>
			{% else %}
			<li>
				<a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
			</li>
			<li>
				<a href="{% url 'signin' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
			</li>
			{% endif %}
		</ul>
		
	</div>
</div>